// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: common/proto/users/users.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServviceClient is the client API for UserServvice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServviceClient interface {
	RegisterUser(ctx context.Context, in *UserRegistrationPayload, opts ...grpc.CallOption) (*RegisterMessage, error)
	LoginUser(ctx context.Context, in *UserLoginPayload, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateRating(ctx context.Context, in *Review, opts ...grpc.CallOption) (*ReviewMessage, error)
}

type userServviceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServviceClient(cc grpc.ClientConnInterface) UserServviceClient {
	return &userServviceClient{cc}
}

func (c *userServviceClient) RegisterUser(ctx context.Context, in *UserRegistrationPayload, opts ...grpc.CallOption) (*RegisterMessage, error) {
	out := new(RegisterMessage)
	err := c.cc.Invoke(ctx, "/proto.UserServvice/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServviceClient) LoginUser(ctx context.Context, in *UserLoginPayload, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.UserServvice/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServviceClient) CreateRating(ctx context.Context, in *Review, opts ...grpc.CallOption) (*ReviewMessage, error) {
	out := new(ReviewMessage)
	err := c.cc.Invoke(ctx, "/proto.UserServvice/CreateRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServviceServer is the server API for UserServvice service.
// All implementations must embed UnimplementedUserServviceServer
// for forward compatibility
type UserServviceServer interface {
	RegisterUser(context.Context, *UserRegistrationPayload) (*RegisterMessage, error)
	LoginUser(context.Context, *UserLoginPayload) (*LoginResponse, error)
	CreateRating(context.Context, *Review) (*ReviewMessage, error)
	mustEmbedUnimplementedUserServviceServer()
}

// UnimplementedUserServviceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServviceServer struct {
}

func (UnimplementedUserServviceServer) RegisterUser(context.Context, *UserRegistrationPayload) (*RegisterMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedUserServviceServer) LoginUser(context.Context, *UserLoginPayload) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedUserServviceServer) CreateRating(context.Context, *Review) (*ReviewMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRating not implemented")
}
func (UnimplementedUserServviceServer) mustEmbedUnimplementedUserServviceServer() {}

// UnsafeUserServviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServviceServer will
// result in compilation errors.
type UnsafeUserServviceServer interface {
	mustEmbedUnimplementedUserServviceServer()
}

func RegisterUserServviceServer(s grpc.ServiceRegistrar, srv UserServviceServer) {
	s.RegisterService(&UserServvice_ServiceDesc, srv)
}

func _UserServvice_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServviceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserServvice/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServviceServer).RegisterUser(ctx, req.(*UserRegistrationPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServvice_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServviceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserServvice/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServviceServer).LoginUser(ctx, req.(*UserLoginPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServvice_CreateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServviceServer).CreateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserServvice/CreateRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServviceServer).CreateRating(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServvice_ServiceDesc is the grpc.ServiceDesc for UserServvice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServvice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserServvice",
	HandlerType: (*UserServviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserServvice_RegisterUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _UserServvice_LoginUser_Handler,
		},
		{
			MethodName: "CreateRating",
			Handler:    _UserServvice_CreateRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/proto/users/users.proto",
}
